### ISSUE TITLE
Can you teach me about Arduino?

### ISSUE THREAD

**Issue by Mr18565433296** [jacobcxdev/NodeMCU-Homebridge-RGB-Controller#1]
Sorry, please ask Arduino how to use it. I brushed it in, but I didn't see esp8266 networking on the router. I've changed the personal settings inside.I'm not sure which one to choose for the example, and other parameters for the brush. Can you tell me? Thank you！

**Comment by jacobcxdev** [comment]
Hello, if I understand correctly what you’re asking, use the NodeMCU esp8266.

This was my eBay shopping basket (bear in mind I live in the UK, so you may want items from different sellers):
https://www.ebay.co.uk/itm/NodeMCU-Lua-ESP8266-Development-Board-ESP12-ESP-12-with-CH340G-USB/323489873231
https://www.ebay.co.uk/itm/L7805CV-5V-Voltage-Regulator-TO-220-x-5-pack-UK-Seller/122977632319
https://www.ebay.co.uk/itm/5X-IRLZ44N-PBF-Power-MOSFET-Logic-Level-N-Channel-0-022OHM-IC-Chip-Transistor-UK/303002244053
https://www.ebay.co.uk/itm/Adafruit-Breadboard-friendly-2-1mm-DC-barrel-jack-ADA373/331584502993
https://www.ebay.co.uk/itm/1-100pcs-3296-Multiturn-Variable-Trimmer-Preset-Resistor-Potentiometer-Pot/231960342000
https://www.ebay.co.uk/itm/Solderless-Breadboard-Prototype-65pc-Jump-Cable-Wires-PCB-Arduino-Raspberry-PI/262575021414

**Comment by Mr18565433296** [comment]
I'm sorry, I didn't express clearly is, in fact, I have to buy good material, but when I use the Arduino (a esp8266 burning software), I found that can burn in your code (ino) but flash the firmware after esp not connected wi-fi, I can't find it in the local area network (LAN) of the IP address, open the serial port monitor will display the code. By the way, could you tell me how to brush the firmware? If you understand what I mean, it will be the best. Thank you!

**Comment by jacobcxdev** [comment]
So when you use the Arduino IDE to flash the NodeMCU, it flashes successfully but the NodeMCU doesn’t connect to the router? If I understand correctly, uncomment lines 107-112 (by removing lines 106 and 113) and reflash the NodeMCU. Once flashed, check the serial monitor to see if it says anything.

**Comment by Mr18565433296** [comment]
Ok, I'll give it a try and contact you again if there are any problems. Thank you for help.

**Comment by jacobcxdev** [comment]
Let me know how it goes.

**Comment by Mr18565433296** [comment]
I tried again in the past，but it still doesn't work，
First，I am not sure if the parameters I set when I swiped the firmware are correct.
Second, I deleted the comment lines and still couldn't find the device in my router.
Maybe my Settings of 84, 85 and 86 were wrong.I really want to realize the connection and transformation of RGB lamp.
 Please help me find out what went wrong. thank you！
   Here are some photos of my attempts.


[image1.png]


[image2.png]


[image3.png]


[image4.png]


[image5.png]

**Comment by jacobcxdev** [comment]
Please update your comment with the images on Github - any attachments sent via email response will not show.

The lines you uncommented enable logging of the WiFi status, they do not fix anything. Check the serial monitor to see whether the NodeMCU is having a hard time connecting to your WiFi etc.

**Comment by Mr18565433296** [comment]
I just started using GitHub. I don't know how to insert the picture. 
So I put the picture in one of my GitHub projects. 
Its name is easy to identify. Can you go and see it? 
Thank you very much！

**Comment by jacobcxdev** [comment]
Ensure you are using the 115200 baud rate for the serial monitor. If you continue to get unintelligible feedback from the serial monitor, try switching through the baud rates in the serial monitor to see if any others work (for whatever reason).

**Comment by Mr18565433296** [comment]
Okay, I'll try again. Before that, please tell me

 "Upload Speed: 115200"
CPU Frequency: 80 MHZ
Crystal Frequency: "26 MHZ
Flash Size: "512K (no SPIFFS)
Flash Mode: "Q10 (fast)
Flash Frequency: "40MHZ
Debug port: "Disabled
Exceptions: "Disabled
Builtin Led: m2“
Erase Flash: "Al Fash Contents"

Is it set correctly?

**Comment by Mr18565433296** [comment]
I've tried to change the baud rate to see if the serial port is displayed properly. It's the fact that it's still scrambling.

**Comment by jacobcxdev** [comment]
IIRC, you should have set the debug port in those settings to enable serial debugging. I’ll check later when I have access to my computer, but keep trying I guess.

**Comment by jacobcxdev** [comment]
See these images for how I got the serial monitor working:

![Serial Monitor](https://user-images.githubusercontent.com/27970288/58570104-41c4c880-822f-11e9-84b9-525137c5c6ea.PNG)
![NodeMCU Flashing Settings](https://user-images.githubusercontent.com/27970288/58570105-41c4c880-822f-11e9-8dec-b00a047c828a.png)
![Uncommented Code](https://user-images.githubusercontent.com/27970288/58570107-41c4c880-822f-11e9-80d8-239ed3bdc85a.PNG)

**Comment by Mr18565433296** [comment]
Can you tell me what I should choose?
When swiping firmware is，
How to select File — Example，
Although everything went well with the brush
I'm not sure I've chosen the right header library.
Thank you.

**Comment by jacobcxdev** [comment]
I'm still not sure what you mean by "Brush" (or "swiping firmware" for that matter).

**Comment by Mr18565433296** [comment]
Sorry, my English is really poor, which has caused you confusion.
Let me reexplain, when I'm ready to compile a File, what Example should I choose,
 it's when you click File -- Example.
Examples for NodeMCU, which one fits your code?

**Comment by Mr18565433296** [comment]
Maybe you can check it out from my onedrive

https://1drv.ms/u/s!Auj8lyWvZ02MsFpDuCwE-uyBiYcX

**Comment by jacobcxdev** [comment]
> Sorry, my English is really poor, which has caused you confusion. Let me reexplain, when I'm ready to compile a File, what Example should I choose, it's when you click File -- Example. Examples for NodeMCU, which one fits your code?

None. You do not use any of those examples. All you do is:

1.  Add `https://arduino.esp8266.com/stable/package_esp8266com_index.json` to the `Additional Board Manager URLs:` input box in `File > Preferences`.
2.  Open `Tools > Board: > Boards Manager` and search for and install `esp8266`.
3.  Select `Tools > Board: > Generic ESP8266 Module`.
4.  Select `Tools > Debug port: > Serial`.
5.  Copy/paste the code from [here](https://raw.githubusercontent.com/jacobcxdev/NodeMCU-Homebridge-RGB-Controller/master/app.ino) into your Arduino IDE sketch.
6.  Follow the instructions in the comments at the top of the code.
7.  Upload to your NodeMCU and check the serial monitor (using whatever baud rate is set in line 152).

**Comment by Mr18565433296** [comment]
Sorry I didn't have time to try again until now.
I found that writing your code still doesn't work with wi-fi.
I tried to write to other firmware (bin),
 and then I found that it could be connected to the Internet,
the serial port monitor showed like this,
 I don't know if I did it correctly.
https://1drv.ms/u/s!Auj8lyWvZ02MsFxXoy0kzhx8Kx7Q

**Comment by Mr18565433296** [comment]
I just try to wrap the ino file as a bin file and then write it through ESP8266Flasher，
and then，It can now connect to my router，It's really amazing.
My sincere thanks to you again.





https://1drv.ms/u/s!Auj8lyWvZ02MsF6DoWdzxvQsualn

**Comment by jacobcxdev** [comment]
I’m glad it worked :). Let me know if you need any further help.

**Comment by Mr18565433296** [comment]
What a pity. I'm having trouble again. When I try to adjust the brightness, it shows that the device is not responding. I have modified index.js

发自我的 iPhone

在 2019年5月30日，下午8:17，Jacob Clayden <notifications@github.com<mailto:notifications@github.com>> 写道：


I’m glad it worked :). Let me know if you need any further help.
